Fix srp_error() (stderr) regression introduced in e26eb9f
In e26eb9f all symbols were set to KSYM_SYNC, meaning klish will run
them in exec_action_sync(), which from what I understand, has their
stdout/stderr output handled differently from exec_action_async(),
and there's where I lost track of the execution.

Before this commit, but after e26eb9f:

    root@infix-12-34-56:/> configure
    [edit]
    root@infix-12-34-56:configure> edit system authentication
    [edit system authentication]
    root@infix-12-34-56:configure> set user admin password fooza
    [edit system authentication]
    root@infix-12-34-56:configure>

After this commit:

    root@infix-12-34-56:/> configure
    [edit]
    root@infix-12-34-56:configure> edit system authentication
    [edit system authentication]
    root@infix-12-34-56:configure> set user admin password fooza
    Error: Unsatisfied pattern - "fooza" does not conform to "$0$.*|$1$[a-zA-Z0-9./]{1,8}$[a-zA-Z0-9./]{22}|$5$(rounds=\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{43}|$6$(rounds=\d+$)?[a-zA-Z0-9./]{1,16}$[a-zA-Z0-9./]{86}". (Schema location "/ietf-system:system/authentication/user/password".)
    Error: Can't set data
    [edit system authentication]
    root@infix-12-34-56:configure>

Hence, this is only a workaround for the loss of stderr, reverting to
run a subset of the commands async.  According to the "Note:" comment
all nav commands should be run sync, so we only reset a subset of the
symbols, ones I believe may have relevant stderr output to the user.

Signed-off-by: Joachim Wiberg <troglobit@gmail.com>